#!/bin/bash
# ...Get the path\name of the markdown file...
MDFILE=$1
MDDIR=$(dirname $MDFILE)
MDNAME=$(basename $MDFILE .md)
# ...Change direction to the markdown file...
cd $MDDIR
# ...run MarTex on the markdown file...
MarTex $MDNAME.md
# ...run TexPdf on the corresponding tex file...
TexPdf $MDNAME.tex