#!/bin/bash
# ...Get the path\name of the markdown file...
MDFILE=$1
MDDIR=$(dirname $MDFILE)
MDNAME=$(basename $MDFILE .md)
# ...Change direction to the markdown file...
cd $MDDIR
# ...run MarTex on the markdown file...
bash <(curl -s https://raw.githubusercontent.com/someonedomath/MarTex/master/MarTex.sh) $MDNAME.md
# ...run TexPdf on the corresponding tex file...
bash <(curl -s https://raw.githubusercontent.com/someonedomath/MarTex/master/TexPdf.sh) $MDNAME.tex